niche/niche/houseplants/urls.py
from django.urls import path

from . import views

app_name = 'houseplants'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:plant_id>/', views.detail, name='detail'),
	path('log', views.log, name='log'),
	path('activities', views.activities, name='activities'),
	path('<int:plant_id>/watering', views.add_water_log, name='water'),
	path('<int:plant_id>/fertilizing', views.add_fertilizer_log, name='fertilize'),
	path('add_plant', views.add_plant, name='add-plant')
]

niche/niche/niche/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('houseplants/', include('houseplants.urls')),
    path('admin/', admin.site.urls),
]

niche/niche/houseplants/models.py
from django.db import models
from datetime import date


# Create your models here.
class Plant(models.Model):
    # english_name = models.TextField(default="", max_length=200)
    # chinese_name = models.TextField(default="", max_length=200)
    scientific_name = models.TextField(max_length=200)
    # date_purchased = models.DateTimeField('date purchased')
    # full_sun = models.BooleanField(default=False)
    # half_sun = models.BooleanField(default=False)
    # shadow = models.BooleanField(default=False)
    # min_temp = models.IntegerField(default=15)
    # max_temp = models.IntegerField(default=42)
    # comfortable_temp = models.IntegerField(default=25)
    # family = models.TextField(default="", max_length=200)
    # comments = models.TextField(default="", max_length=1000)

    def __str__(self):
        return self.scientific_name


# Keeping Track of the different possible activities.
class Activity(models.Model):
    name = models.TextField(default=" ", max_length=50)
    description = models.TextField(default="Activity Description", max_length=200)

    def __str__(self):
        return self.name


# Tracking information about the plants.
class PlantLog(models.Model):
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE)
    date = models.DateField(default=date.today())
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s %s" % (self.date, self.plant, self.activity)
    
    class Meta:
        ordering = ['date']

    

niche/niche/houseplants/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.timezone import now
from django.http import JsonResponse, HttpResponse
import json

from .models import Plant, Activity, PlantLog


def index(request):
    plant_list = Plant.objects.order_by('scientific_name')
    watering_list = PlantLog.objects.order_by('date').last
    fertilize_list = PlantLog.objects.order_by('date').last
    context = {'plant_list': plant_list, 'watering_list': watering_list, 'fertilize_list': fertilize_list }
    return render(request, 'houseplants/index.html', context)


def detail(request, plant_id):
    plant = get_object_or_404(Plant, pk=plant_id)
    last_watering = PlantLog.objects.filter(plant=plant_id, activity='1').order_by('date').last
    last_fertilized = PlantLog.objects.filter(plant=plant_id, activity='2').order_by('date').last
    return render(request, 'houseplants/detail.html', {'plant': plant, 'last_watering': last_watering, 'last_fertilized': last_fertilized})


def log(request):
    log_list = PlantLog.objects.order_by('-date')
    context = {
        'log_list': log_list
        }
    return render(request, 'houseplants/log.html', context)


def activities(request):
    activity_list = Activity.objects.order_by('id')
    context = {
        'activity_list': activity_list
        }
    return render(request, 'houseplants/activities.html', context)


def add_water_log(request, plant_id):
    print("Add Water Getting Called")
    if request.method == 'POST':
        print(f'Plant: {plant_id}')
        # plant = Plant.objects.get(pk=plant_id).scientific_name
        print(now())
        watering = PlantLog(plant=Plant.objects.get(pk=plant_id), date=now(), activity=Activity.objects.get(pk='1'))
        watering.save()
        data = {
            'plant': plant_id,
            'date': now(),
            'activity': '1'
        }
        return JsonResponse(data, status=200)
    else:
        return JsonResponse({"error": "Please contact your administrator."}, status=400)


def add_fertilizer_log(request, plant_id):
    if request.method == 'POST':
        fertilizer = PlantLog(plant=Plant.objects.get(pk=plant_id), date=now(), activity=Activity.objects.get(pk='2'))
        fertilizer.save()
        data = {
            'plant': plant_id,
            'date': now(),
            'activity': '1'
        }
        return JsonResponse(data, status=200)
    else:
        return JsonResponse({"error": "Please contact your administrator."}, status=400)


def add_plant(request):
    return render(request, 'houseplants/addPlant.html')

niche/niche/houseplants/templates/houseplants/activities.html
{% extends "houseplants/base.html" %}
{% load i18n %}
{% block content %}
{% if activity_list %}
<div class="container">
<h1>{% trans "Activity Table" %}</h1>
  <p>{% trans "These are the possible activities, you can do with a plant" %}:</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "ID" %}</th>
        <th>{% trans "Activity" %}</th>
        <th>{% trans "Description" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for activity in activity_list %}
      <tr>
        <td>{{ activity.id }}</td>
        <td>{{ activity.name }}</td>
        <td>{{ activity.description }}<td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
    <p>{% trans "No activities available" %}.</p>
{% endif %}
{% endblock content %}

niche/niche/houseplants/templates/houseplants/addPlant.html
<h1>Add Plant</h1>

niche/niche/houseplants/templates/houseplants/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Niche - {% trans "Plant Inventory" %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script>
  $(document).ready(function() {
      $('#fertilizer_button').click(function(data){
          console.log("Fertilizer button pessed")
    });
    $('#add-plant').click(function(data){
          console.log("Add plant button pressed")
    });
  });
</script>
</head>
<body>
<header class="site-header">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'houseplants:index' %}">Niche</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'houseplants:log' %}">{% trans "Plant Log" %}</a></li>
      <li class="active"><a href="{% url 'houseplants:index' %}">{% trans "Plant Inventory" %}</a></li>
      <li class="active"><a href="{% url 'houseplants:activities' %}">{% trans "Activities" %}</a></li>
    </ul>
  </div>
</nav>
</header>
<main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

niche/niche/houseplants/templates/houseplants/detail.html
{% extends "houseplants/base.html" %}
{% load i18n %}
{% block content %}
<div class="containter">
    <div>
        <img src="https://media.giphy.com/media/WPtzVOKMymmZrJv8fO/giphy.gif" alt="Flowering Dino" width="250" height="250">
        <p>{% trans "Scientific Name"%}:</p><p>{{ plant }}</p>
    </div>
    <div>
        <p>{% trans "Last watering Date" %}:</p><p>{{ last_watering.date }}</p>
        <p>{% trans "Last fertilized Date" %}:</p><p>{{ last_fertilized.date }}</p>
    </div>
    <form action="{% url 'houseplants:water' plant.id %}" method="post">
        {% csrf_token %}
        <input type="submit" id="water_button" value="{% trans "Watering" %}">
    </form>
     <form action="{% url 'houseplants:fertilize' plant.id %}" method="post">
        {% csrf_token %}
        <input type="submit" id="fertilizer_button" value="{% trans "Fertilizer" %}">
    </form>
</div>
{% endblock content %}

niche/niche/houseplants/templates/houseplants/index.html
{% extends "houseplants/base.html" %}
{% load i18n %}
{% block content %}
{% if plant_list %}
<div class="container">
<h1>{% trans "Plant Table"%}</h1>
  <p>{% trans "This table contains all the plants" %}</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "Plant ID" %}</th>
        <th>{% trans "Scientific Name" %}</th>
        <th>{% trans "Last Water Date" %}</th>
        <th>{% trans "Last Fertilized Date" %}<th>
      </tr>
    </thead>
    <tbody>
    {% for plant in plant_list %}
      <tr>
        <td>{{ plant.id }}</td>
        <td><a href="{% url 'houseplants:detail' plant.id %}">{{ plant.scientific_name }}</a></td>
        <td>{{ watering_list.date }}</td>
        <td>{{ fertilize_list.date }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<button type="button" id="add-plant" href="href="{% url 'houseplants:log' %}">Add Plant</button>
{% else %}
    <p>No plants available.</p>
    <button type="button" id="add-plant" href="{% url 'houseplants:add-plant' %}">Add Plant</button>
{% endif %}
{% endblock content %}

niche/niche/houseplants/templates/houseplants/log.html
{% extends "houseplants/base.html" %}
{% load i18n %}
{% block content %}
{% if log_list %}
<div class="container">
<h1>{% trans "Plant Log Table" %}</h1>
  <p>{% trans "This table contains a log about all activites on that plant" %}:</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Plant Name" %}</th>
        <th>{% trans "Activity" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for entry in log_list %}
      <tr>
        <td>{{ entry.date }}</td>
        <td><a href="{% url 'houseplants:detail' entry.plant.id %}">{{ entry.plant.scientific_name }}</a></td>
        <td>{{ entry.activity }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% else %}
    <p>{% trans "No plants available" %}.</p>
{% endif %}
{% endblock content %}